# Importing a Libraries

In [ ]:
import pandas as pd
import numpy as np

# Importing Data Set from read_csv

In [ ]:
data=pd.read_csv('placement.csv')
data

# Import the file from Server using StringIo

In [ ]:
import requests
from io import StringIO
'''
url="Url Link"
header=" "
req=requests.get(url,headers=header)
data=StringIO(req.txt)
df=pd.read_csv(data)
'''

'\nurl="Url Link"\nheader=" "\nreq=requests.get(url,headers=header)\ndata=StringIO(req.txt)\ndf=pd.read_csv(data)\n'

# Sep Parameter Use
### Sep='[no of parameter to avoids']

In [ ]:
data=pd.read_csv('practise.csv', sep=';')
data

    Name  Age    City
0  Rahul   21   Delhi
1   Aman   22  Mumbai
2   Sara   20    Pune

In [ ]:
data = """totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4"""

with open('sample.csv','w') as file:
  file.write(data)

df=pd.read_csv('sample.csv',sep='[:|_,]',engine='python')
df

   totalbill   tip      sex smoker   day     time   size
0      16.99  1.01   Female     No   Sun   Dinner      2
1      10.34  1.66     Male     No   Sun   Dinner      3
2      21.01  3.50     Male     No   Sun   Dinner      3
3      23.68  3.31     Male     No   Sun   Dinner      2
4      24.59  3.61   Female     No   Sun   Dinner      4
5      25.29  4.71     Male     No   Sun   Dinner      4

# Header Parameter
### data=pd.read_csv('test.csv', header=n)
### where n+1=where to start a rows
### This function is used to when we have to decide from which row we have to start the data.

# Use Column Technique
### data=pd.read_csv('test.csv', usecols=['Columne1','Columne2',.....])

# Index a Column
### df = pd.read_csv("people.csv", index_col="Column name")

# Select the Data upto N row
### df = pd.read_csv('people.csv', nrows=n)
### where n=upto we have to choose row

# SkipRows
### df = pd.read_csv('people.csv', skiprows = [n1,n2,...])
### n1,n2... the row index you want to skip

# Encoding a Data
### df = pd.read_csv("data.csv", encoding="encoding parameter name")
### Common Encoding Types

| Encoding | Use |
|----------|-----|
| utf-8 | Most common, supports all languages |
| latin1 | Used for Western European text |
| cp1252 | Windows default encoding |
| utf-16 | Large Unicode files |

# dtypes Parameter
### df=pd.read_csv('sample.csv',dtypes={'Column Name':data type}).info()
### we use this parameter if we have change certain column data types.

# Handling a dates
### df=pd.read_csv('sample.csv',parse_dates=['dates']).info()
### This paramter is used to dates from into datatime value data types

# Convertor Parameter
### df=pd.read_csv(ipl.csv,converter={'column name':rename})
### def rename(name):
###     if name == 'Old name':
###        return 'New Name'
###     else
###        return name
### rename('Old Name')